### ISSUE TITLE
加载 .bin 文件的时候报错了

### ISSUE THREAD

**Issue by py-zhao** [ttcong194/CocosToSingleHTML5#1]
这个bin文件应该是个球的模型  fbx 格式  ,不用这个模型 ,用cocos 自带的球体模型也不行.

=================== Start to Integrate Res into Html ====================
--------F:\Project\SingleHTML\Shooting_V\html_generator/../build/web-mobile/index.html
--------F:\Project\SingleHTML\Shooting_V\html_generator/../build/web-mobile/src/settings.js
.
.
.
--------F:\Project\SingleHTML\Shooting_V\html_generator/../build/web-mobile/assets/main/import/06/06a17fb07.json
--------F:\Project\SingleHTML\Shooting_V\html_generator/../build/web-mobile/assets/main/native/03/03829c68-008b-4e80-92df-87f17a3e0fe2.bin
Traceback (most recent call last):
  File "F:\Project\SingleHTML\Shooting_V\html_generator\generate_single_html.py", line 26, in <module>
    generate_html(need2TinifyPic)
  File "F:\Project\SingleHTML\Shooting_V\html_generator\generate_single_html.py", line 18, in generate_html
    integrate_res_in_html.integrate(projectRootPath)
  File "F:\Project\SingleHTML\Shooting_V\html_generator\integrate_res_in_html.py", line 111, in integrate
    resStr = getResMapScript(resPath)
  File "F:\Project\SingleHTML\Shooting_V\html_generator\integrate_res_in_html.py", line 72, in getResMapScript
    getResMap(jsonObj, resPath, resPath)
  File "F:\Project\SingleHTML\Shooting_V\html_generator\integrate_res_in_html.py", line 63, in getResMap
    getResMap(jsonObj, absPath, resPath)
  File "F:\Project\SingleHTML\Shooting_V\html_generator\integrate_res_in_html.py", line 63, in getResMap
    getResMap(jsonObj, absPath, resPath)
  File "F:\Project\SingleHTML\Shooting_V\html_generator\integrate_res_in_html.py", line 63, in getResMap
    getResMap(jsonObj, absPath, resPath)
  File "F:\Project\SingleHTML\Shooting_V\html_generator\integrate_res_in_html.py", line 65, in getResMap
    dataStr = read_in_chunks(absPath)
  File "F:\Project\SingleHTML\Shooting_V\html_generator\integrate_res_in_html.py", line 52, in read_in_chunks
    return file_object.read()
  File "D:\Program Files\Python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 2: invalid start byte

**Comment by py-zhao** [comment]
[3bbdb0f6-c5f6-45de-9f33-8b5cbafb4d6d.zip](https://github.com/ttcong194/Cocos-to-PlayableAd-HTML5/files/6921562/3bbdb0f6-c5f6-45de-9f33-8b5cbafb4d6d.zip)

这种bin文件

**Comment by ttcong194** [comment]
@Luckeee  What is is your bin file? I only just test on 2d project.

**Comment by SindujaRajadurai** [comment]
Any luck on loading 3d models?
